parameters:
- name: application
  type: string
  default: airq
- name: envName
  type: string
- name: location
  type: string
  default: northcentralus
- name: sku
  type: string
  default: F1
- name: azureResourceManagerConnection
  type: string
  default: MSDN

stages:
- stage: ${{ parameters.envName }}
  variables:
    - group: '${{ parameters.application }}-${{ parameters.envName }}'
  jobs:
  - deployment: ${{ parameters.envName }}
    displayName: Deploy ${{ parameters.application }} to ${{ parameters.envName }}
    environment:
      name: ${{ parameters.envName }}
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: '${{ parameters.azureResourceManagerConnection }}'
              subscriptionId: '$(subscriptionId)'
              action: 'Create Or Update Resource Group'
              resourceGroupName: '${{ parameters.application }}-${{ parameters.envName }}'
              location: ${{ parameters.location }}
              templateLocation: 'Linked artifact'
              csmFile: template.json
              #overrideParameters: # Optional
              deploymentMode: 'Incremental'
              #outputVariable: # Optional
              #deploymentName: # Optional
              #deploymentOutputs: # Optional
